### ISSUE TITLE
Memory size

### ISSUE THREAD

**Issue by szogi1910** [ToxicRevolution/CSGORankMeWeb#13]
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 8192 bytes) in /home/pggames/domains/project/public_html/statystyki/dd2mirage/control/queryFunctions.php on line 47

**Comment by kennyLtv** [comment]
How many players are in your database?

**Comment by szogi1910** [comment]
12797 Total Users!

**Comment by APet74** [comment]
Kenny or I can send you a fix. Or Kenny so you wanna give him the old version of queryfunctions and the leaderboard pages as well the players class. I can write a fix tomorrow.

**Comment by szogi1910** [comment]
Ok, I'll wait for the fix

**Comment by szogi1910** [comment]
And how will it with this?

**Comment by APet74** [comment]
Sorry, been busy with school starting. I am looking into server-side pagination and that will hopefully speed things up AND fix your error. Sorry for the delay.

**Comment by APet74** [comment]
@szogi1910 Please download a new ZIP of the project. I have added a new file in /control/leaderboard named leaderboardGrabLarge.php, please replace your leaderboardGrab.php with that file making sure to rename it to "leaderboardGrab.php". I have added the necessary functions to queryFunctions.php so that will need to be moved too. As always I suggest a full replacement of the file system followed by you deleting the install directory. Overwriting all your files will cause no harm. Please let me know if there is more.

Thanks.

**Comment by szogi1910** [comment]
It now shows all players
Only now is the problem of retrieving data for the score column
Example player via www max pkt 1012 - http://imgur.com/a/NUW7x 

Top players via www
http://project-games.eu/statystyki/dd2mirage/leaderboards.php - http://i.imgur.com/aNnMxH0.png
To players rekords pma - https://i.imgur.com/Ppkhro4.png

**Comment by APet74** [comment]
So basically you're saying that the database shows a different number in
the score column versus what the website shows. That's very interesting I
don't know what would cause that because the script literally just pulls
from the score column, I'll have to look into it and see if I can figure
out what would be causing that. Do you have more than one rankme database,
is there any other databases.

**Comment by kennyLtv** [comment]
Is it possible that you are pulling from an incorrect database now? https://puu.sh/xjy2p/58d0818185.png as it shows the same thing on the profile page.

**Comment by APet74** [comment]
I just don't know how it is pulling wrong. All other people using it have
not reporting any problems.

**Comment by szogi1910** [comment]
@APet74 There, I have several rankme tables each have a separate prefix
@kennyLtv I checked twice and the data I have in config and are correct


Here you can see the version that works without the last fix and gets the data correctly
http://project-games.eu/statystyki/dd2/leaderboards.php

**Comment by APet74** [comment]
I have made a change that should resolve it. For our own records, the issue
was within the SQL statement of queryFunctions.php, the statement had
`WHERE kills = 0 AND deaths = 0` instead of `WHERE kills <> 0 AND deaths <>
0` Please check now and let me know.

**Comment by szogi1910** [comment]
Gets data correctly.
Thanks for taking the time and adding a fix.

**Comment by szogi1910** [comment]
The problem reappeared
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /home/pggames/domains/project-games.eu/public_html/statystyki/dd2/control/queryFunctions.php on line 47
