### ISSUE TITLE
Migrate PHP to Symfony framework

### ISSUE THREAD

**Issue by b3none** [ToxicRevolution/CSGORankMeWeb#31]
At some point I might just push all of this over to Symfony so it is much cleaner and easier to follow :+1:

**Comment by kennyLtv** [comment]
I have been working on moving it to Laravel with a SPA for the UI. Actually, I have been doing a little more than considering it, you can see it [Here](https://github.com/ToxicRevolution/RankMeReact). It is still really rough and not really at working standpoint. But I guess that is what happens when you try to work on to many things at a time...

**Comment by b3none** [comment]
Eww, Laravel :mask: I can write Laravel and if you set it up I will happily write some PHP / an API for people to query their statistics or something. I could make a forum signature style system. Just let me know when it is ready and I'll write it :)

**Comment by kennyLtv** [comment]
I'll let you know when it's out of early development, it's sorta on a backburner for me as I have 4 or 5 other open projects too that I am trying to work on. Also out of curiosity what don't you like about Laravel?
